services:
  pps8-operators-webapp:
    container_name: digitalforce-web
    build:
      context: .
    image: pps8-operators-webapp:latest
    restart: always
    networks:
      - common_network

networks:
  common_network:
    external: true
